services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    volumes:
      - .:/app
    depends_on:
      - oracle-db

  oracle-db:
    image: gvenzl/oracle-xe:latest
    environment:
      - ORACLE_PASSWORD=123
      - APP_USER=pablo
      - APP_USER_PASSWORD=123
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:  # Esta sección debe estar al mismo nivel que services
  oracle-data:
