DROP TABLE DETALLE_TRASLADO_PRODUCTOS CASCADE CONSTRAINTS;
DROP TABLE TRASLADO_PRODUCTOS CASCADE CONSTRAINTS;
DROP TABLE DEVOLUCIONES CASCADE CONSTRAINTS;
DROP TABLE ENVIOS CASCADE CONSTRAINTS;
DROP TABLE EMPRESAS_TRANSPORTE CASCADE CONSTRAINTS;
DROP TABLE PAGOS CASCADE CONSTRAINTS;
DROP TABLE DETALLE_ORDEN CASCADE CONSTRAINTS;
DROP TABLE ORDEN_COMPRA CASCADE CONSTRAINTS;
DROP TABLE IMAGENES CASCADE CONSTRAINTS;
DROP TABLE INVENTARIO CASCADE CONSTRAINTS;
DROP TABLE PRODUCTOS CASCADE CONSTRAINTS;
DROP TABLE CATEGORIAS CASCADE CONSTRAINTS;
DROP TABLE TRABAJADORES CASCADE CONSTRAINTS;
DROP TABLE SEDES CASCADE CONSTRAINTS;
DROP TABLE CARGOS CASCADE CONSTRAINTS;
DROP TABLE DEPARTAMENTOS CASCADE CONSTRAINTS;
DROP TABLE METODOS_PAGO_USUARIO CASCADE CONSTRAINTS;
DROP TABLE METODOS_PAGO CASCADE CONSTRAINTS;
DROP TABLE DIRECCIONES CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;

-- Tabla Usuarios
CREATE TABLE usuarios (
    Id_Usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Rol VARCHAR2(20) NOT NULL CHECK (Rol IN ('Cliente', 'Trabajador')),
    Identificacion_Nacional VARCHAR2(50) UNIQUE NOT NULL,
    Nombre VARCHAR2(100) NOT NULL,
    Apellido VARCHAR2(100) NOT NULL,
    Correo VARCHAR2(150) UNIQUE NOT NULL,
    Contrasena VARCHAR2(255) NOT NULL,
    Telefono VARCHAR2(20) NOT NULL,
    Estado VARCHAR2(20) DEFAULT 'Activo' CHECK (Estado IN ('Activo', 'Inactivo')),
    Fecha_Registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Estado_Correo VARCHAR2(20) DEFAULT 'No Confirmado' CHECK (Estado_Correo IN ('Confirmado', 'No Confirmado')),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Verificación de creación
SELECT table_name FROM user_tables WHERE table_name = 'USUARIOS';

-- Tabla Departamentos (sin dependencias)
CREATE TABLE departamentos (
    Id_Departamento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) UNIQUE NOT NULL,
    Descripcion CLOB,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla Cargos (sin dependencias)
CREATE TABLE cargos (
    Id_Cargo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) UNIQUE NOT NULL,
    Descripcion CLOB,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla Sedes (sin dependencias)
CREATE TABLE sedes (
    Id_Sede NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Direccion CLOB NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla Categorias (sin dependencias)
CREATE TABLE categorias (
    Id_Categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(255) NOT NULL,
    Descripcion CLOB,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla Métodos de Pago (sin dependencias)
CREATE TABLE metodos_pago (
    Id_Metodo_Pago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Descripcion CLOB,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla Empresas_Transporte (sin dependencias)
CREATE TABLE empresas_transporte (
    Id_Empresa_Transporte NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(255) NOT NULL,
    Informacion_Contacto CLOB NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla Direcciones (depende de usuarios)
CREATE TABLE direcciones (
    Id_Direccion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_Usuario NUMBER NOT NULL,
    Direccion CLOB NOT NULL,
    Tipo VARCHAR2(20) NOT NULL CHECK (Tipo IN ('Envío', 'Facturación')),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dir_usuario FOREIGN KEY (Id_Usuario) REFERENCES usuarios(Id_Usuario)
);

-- Tabla Trabajadores (depende de usuarios, cargos, departamentos, sedes)
CREATE TABLE trabajadores (
    Id_Trabajador NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_Usuario NUMBER NOT NULL,
    Id_Cargo NUMBER,
    Id_Departamento NUMBER,
    Correo_Institucional VARCHAR2(150) UNIQUE NOT NULL,
    Id_Sede NUMBER,
    Estado VARCHAR2(20) DEFAULT 'Activo' CHECK (Estado IN ('Activo', 'Inactivo')),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trab_usuario FOREIGN KEY (Id_Usuario) REFERENCES usuarios(Id_Usuario),
    CONSTRAINT fk_trab_cargo FOREIGN KEY (Id_Cargo) REFERENCES cargos(Id_Cargo),
    CONSTRAINT fk_trab_departamento FOREIGN KEY (Id_Departamento) REFERENCES departamentos(Id_Departamento),
    CONSTRAINT fk_trab_sede FOREIGN KEY (Id_Sede) REFERENCES sedes(Id_Sede)
);

-- Tabla Métodos de Pago de Usuario (depende de usuarios, metodos_pago)
CREATE TABLE metodos_pago_usuario (
    Id_Metodo_Pago_Usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_Usuario NUMBER NOT NULL,
    Id_Metodo_Pago NUMBER NOT NULL,
    Detalles CLOB,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mpu_usuario FOREIGN KEY (Id_Usuario) REFERENCES usuarios(Id_Usuario),
    CONSTRAINT fk_mpu_metodo FOREIGN KEY (Id_Metodo_Pago) REFERENCES metodos_pago(Id_Metodo_Pago)
);

-- Tabla Productos (depende de categorias)
CREATE TABLE productos (
    Id_Producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Sku VARCHAR2(50) UNIQUE NOT NULL,
    Nombre VARCHAR2(255) NOT NULL,
    Descripcion CLOB,
    Precio NUMBER(10,2) NOT NULL,
    Slug VARCHAR2(255) UNIQUE NOT NULL,
    Id_Categoria NUMBER NOT NULL,
    Disponibilidad NUMBER(1) DEFAULT 1 CHECK (Disponibilidad IN (0, 1)),
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prod_categoria FOREIGN KEY (Id_Categoria) REFERENCES categorias(Id_Categoria)
);

-- Tabla Inventario (depende de productos, sedes)
CREATE TABLE inventario (
    Id_Inventario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_Producto NUMBER NOT NULL,
    Id_Sede NUMBER NOT NULL,
    Cantidad NUMBER DEFAULT 0,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inv_producto FOREIGN KEY (Id_Producto) REFERENCES productos(Id_Producto),
    CONSTRAINT fk_inv_sede FOREIGN KEY (Id_Sede) REFERENCES sedes(Id_Sede)
);

-- Tabla Imagenes (depende de productos)
CREATE TABLE imagenes (
    Id_Imagen NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_Producto NUMBER NOT NULL,
    Url_Imagen CLOB NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_img_producto FOREIGN KEY (Id_Producto) REFERENCES productos(Id_Producto)
);

-- Tabla Orden_Compra (depende de usuarios)
CREATE TABLE orden_compra (
    Id_Orden NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_Usuario NUMBER NOT NULL,
    Fecha_Creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Estado VARCHAR2(50) NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orden_usuario FOREIGN KEY (Id_Usuario) REFERENCES usuarios(Id_Usuario)
);

-- Tabla Detalle_Orden (depende de orden_compra, productos)
CREATE TABLE detalle_orden (
    Id_Detalle NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_Orden NUMBER NOT NULL,
    Id_Producto NUMBER NOT NULL,
    Cantidad NUMBER NOT NULL,
    Precio_Unitario NUMBER(10,2) NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_detalle_orden FOREIGN KEY (Id_Orden) REFERENCES orden_compra(Id_Orden),
    CONSTRAINT fk_detalle_producto FOREIGN KEY (Id_Producto) REFERENCES productos(Id_Producto)
);

-- Tabla Pagos (depende de orden_compra, metodos_pago)
CREATE TABLE pagos (
    Id_Pago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_Orden NUMBER NOT NULL,
    Fecha_Transaccion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Id_Metodo_Pago NUMBER NOT NULL,
    Estado VARCHAR2(50) NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pago_orden FOREIGN KEY (Id_Orden) REFERENCES orden_compra(Id_Orden),
    CONSTRAINT fk_pago_metodo FOREIGN KEY (Id_Metodo_Pago) REFERENCES metodos_pago(Id_Metodo_Pago)
);

-- Tabla Envios (depende de orden_compra, direcciones, empresas_transporte)
CREATE TABLE envios (
    Id_Envio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_Orden NUMBER NOT NULL,
    Fecha_Despacho TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Id_Direccion NUMBER NOT NULL,
    Id_Empresa_Transporte NUMBER NOT NULL,
    Numero_Seguimiento VARCHAR2(255) UNIQUE NOT NULL,
    Estado VARCHAR2(50) NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_envio_orden FOREIGN KEY (Id_Orden) REFERENCES orden_compra(Id_Orden),
    CONSTRAINT fk_envio_direccion FOREIGN KEY (Id_Direccion) REFERENCES direcciones(Id_Direccion),
    CONSTRAINT fk_envio_transporte FOREIGN KEY (Id_Empresa_Transporte) REFERENCES empresas_transporte(Id_Empresa_Transporte)
);

-- Tabla Devoluciones (depende de orden_compra)
CREATE TABLE devoluciones (
    Id_Devolucion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_Orden NUMBER NOT NULL,
    Fecha_Solicitud TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Motivo CLOB NOT NULL,
    Estado VARCHAR2(50) NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_devolucion_orden FOREIGN KEY (Id_Orden) REFERENCES orden_compra(Id_Orden)
);

-- Tabla Traslado_Productos (depende de sedes, empresas_transporte)
CREATE TABLE traslado_productos (
    Id_Traslado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Fecha_Movimiento TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Id_Sede_Origen NUMBER NOT NULL,
    Id_Sede_Destino NUMBER NOT NULL,
    Estado VARCHAR2(50) NOT NULL,
    Fecha_Estimada_Llegada TIMESTAMP,
    Id_Empresa_Transporte NUMBER NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_traslado_origen FOREIGN KEY (Id_Sede_Origen) REFERENCES sedes(Id_Sede),
    CONSTRAINT fk_traslado_destino FOREIGN KEY (Id_Sede_Destino) REFERENCES sedes(Id_Sede),
    CONSTRAINT fk_traslado_transporte FOREIGN KEY (Id_Empresa_Transporte) REFERENCES empresas_transporte(Id_Empresa_Transporte)
);

-- Tabla Detalle_Traslado_Productos (depende de traslado_productos, productos)
CREATE TABLE detalle_traslado_productos (
    Id_Detalle_Traslado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_Traslado NUMBER NOT NULL,
    Id_Producto NUMBER NOT NULL,
    Cantidad_Transferida NUMBER NOT NULL,
    Estado_Producto VARCHAR2(50) NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dtp_traslado FOREIGN KEY (Id_Traslado) REFERENCES traslado_productos(Id_Traslado),
    CONSTRAINT fk_dtp_producto FOREIGN KEY (Id_Producto) REFERENCES productos(Id_Producto)
);

-- Verificar que todas las tablas fueron creadas
SELECT table_name FROM user_tables 
WHERE table_name IN (
    'USUARIOS', 'DIRECCIONES', 'METODOS_PAGO', 'METODOS_PAGO_USUARIO',
    'DEPARTAMENTOS', 'CARGOS', 'SEDES', 'TRABAJADORES',
    'CATEGORIAS', 'PRODUCTOS', 'INVENTARIO', 'IMAGENES',
    'ORDEN_COMPRA', 'DETALLE_ORDEN', 'PAGOS', 'EMPRESAS_TRANSPORTE',
    'ENVIOS', 'DEVOLUCIONES', 'TRASLADO_PRODUCTOS', 'DETALLE_TRASLADO_PRODUCTOS'
);